# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-18 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('Usuarios', '0002_auto_20170215_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='auth.Group'),
        ),
    ]
