# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-21 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('contenido', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tags', models.CharField(choices=[('TC', 'Tecnología'), ('CT', 'Científico'), ('PR', 'Programación')], max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Publicaciones/')),
            ],
        ),
    ]
